"""add_owner_to_gameroom

Revision ID: 03488f930e63
Revises: df4d74fa4e60
Create Date: 2025-07-30 13:53:06.925058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03488f930e63'
down_revision: Union[str, None] = 'df4d74fa4e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamerooms', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gamerooms', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamerooms', type_='foreignkey')
    op.drop_column('gamerooms', 'owner_id')
    # ### end Alembic commands ###
